{
 "title": "RaspberryPi VPN",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "panels": [
  { "title": "OpenVPN", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Connections",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "openvpn_connections", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Bytes Transmitted",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 9, "x": 6, "y": 1 },
   "targets": [
    {
     "expr": "sum by(common_name) (irate(openvpn_bytes{direction=\"transmit\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Bytes Received",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 15, "y": 1 },
   "targets": [
    {
     "expr": "sum by(common_name) (irate(openvpn_bytes{direction=\"receive\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Ethernet Network IO",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "irate(system_network_io{device=\"eth0\"}[$__interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "VPN Tunnel Network IO",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 7 },
   "targets": [
    {
     "expr": "irate(system_network_io{device=\"tun0\"}[$__interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Network Errors",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 7 },
   "targets": [
    {
     "expr": "sum by(device) (irate(system_network_errors{device=\"eth0\"}[5m]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(device) (irate(system_network_errors{device=\"tun0\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Network Dropped Packets",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 7 },
   "targets": [
    {
     "expr": "sum by(device) (irate(system_network_dropped{device=\"eth0\"}[5m]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(device) (irate(system_network_dropped{device=\"tun0\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU and Processes",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true
  },
  {
   "title": "CPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "1 - avg(irate(system_cpu_time{state=\"idle\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Processes Created",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "irate(system_processes_created[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Process Count",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(status) (system_processes_count)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Temperature",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "raspberry_pi_thermal_zone_temperature",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true
  },
  {
   "title": "Memory Free",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "system_memory_usage{state=\"free\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Used",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "system_memory_usage{state=\"used\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Cached",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "system_memory_usage{state=\"cached\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Buffered",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "system_memory_usage{state=\"buffered\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk IO",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "collapsed": true
  },
  {
   "title": "Disk Operations",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "avg(irate(system_disk_operations[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk Operations Time",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "avg(irate(system_disk_operation_time[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk Pending Operations",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "avg(irate(system_disk_pending_operations[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk IO Time",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "avg(irate(system_disk_io_time[5m]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}